==============================
Test cases for 7-base_geometry
==============================

	>>> BaseGeometry = __import__('7-base_geometry').BaseGeometry

	>>> bg = BaseGeometry()

area method tests:
	
	>>> bg.area()
	Traceback (most recent call last):
	Exception: area() is not implemented

	>>> bg.area(99)
	Traceback (most recent call last):
	TypeError: area() takes 1 positional argument but 2 were given
	
	>>> bg.area(8, 3)
	Traceback (most recent call last):
    	TypeError: area() takes 1 positional argument but 3 were given

Normal integer_validator cases:

	>>> bg.integer_validator("my_int", 12)
	>>> bg.integer_validator("my_int", 12)

Non int cases:

	>>> bg.integer_validator("my_int", True)
	Traceback (most recent call last):
	TypeError: my_int must be an integer

	>>> bg.integer_validator("name", "John")
	Traceback (most recent call last):
	TypeError: name must be an integer

	>>> bg.integer_validator("kids", ['kid1', 'kid2'])
	Traceback (most recent call last):
	TypeError: kids must be an integer

	>>> bg.integer_validator("kids", (5,))
	Traceback (most recent call last):
	TypeError: kids must be an integer

	>>> bg.integer_validator("kids", {2, 7})
	Traceback (most recent call last):
	TypeError: kids must be an integer

	>>> bg.integer_validator("width", None) 
	Traceback (most recent call last):
	TypeError: width must be an integer

less than or equal to 0 cases:

	>>> bg.integer_validator("age", 0)
	Traceback (most recent call last):
	ValueError: age must be greater than 0

	>>> bg.integer_validator("distance", -4)
	Traceback (most recent call last):
	ValueError: distance must be greater than 0

wrong number of args for integer_validator:

	>>> bg.integer_validator()
	Traceback (most recent call last):
	TypeError: integer_validator() missing 2 required positional arguments: 'name' and 'value'

	>>> bg.integer_validator("age", 0, 6)
	Traceback (most recent call last):
	TypeError: integer_validator() takes 3 positional arguments but 4 were given

	>>> bg.integer_validator("age")
	Traceback (most recent call last):
	TypeError: integer_validator() missing 1 required positional argument: 'value'
